# Generated by Django 3.0.5 on 2020-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.TextField()),
                ('nick_name', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=266)),
                ('dislike', models.CharField(max_length=266)),
                ('message', models.CharField(max_length=266)),
                ('gift', models.CharField(max_length=266)),
                ('last_word', models.CharField(max_length=266)),
                ('image', models.ImageField(upload_to='pics')),
                ('video', models.FileField(null=True, upload_to='videos')),
            ],
        ),
    ]
