# Generated by Django 3.0.5 on 2020-05-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='relation',
            new_name='relat',
        ),
    ]
