# Generated by Django 3.0.5 on 2020-05-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200520_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='relat',
            new_name='relationship',
        ),
    ]
